/**
 * 手工编写的示例 TVIR trace（实施手册 §8 要求：创建 example TVIR trace）。
 * 用于测试与演示：前端只消费 TVIR，与事件来自仿真器还是手写无关。
 */

import type { TVIRTrace } from './types';

export const EXAMPLE_TVIR_TRACE: TVIRTrace = {
  description: '手写示例 trace：4×4 GEMM 的最小教学片段（非仿真引擎生成）',
  events: [
    {
      id: 'event-0',
      step: 0,
      type: 'GEMM_START',
      title: 'GEMM 开始：C = A × B',
      what: '准备计算 C = A × B，A、B 均为 4×4 矩阵。',
      why: 'GEMM 是 Transformer 的核心计算，先理解最小规模的一次执行。',
      metadata: { M: 4, N: 4, K: 4 },
    },
    {
      id: 'event-1',
      step: 1,
      type: 'TILE_CREATE',
      title: '矩阵切分为 Tile',
      what: '把 A、B、C 各切成 1 个 4×4 的 Tile。',
      why: 'Tiling 让每个 Block 只需处理一小块数据，提高数据复用。',
    },
    {
      id: 'event-2',
      step: 2,
      type: 'KERNEL_LAUNCH',
      title: '启动 CUDA Kernel',
      what: '启动 GEMM kernel，Grid 中共 1 个 Thread Block。',
      why: 'GPU 通过 Grid 把计算拆成 Block 并行执行。',
      kernel: 'gemm_tiled_kernel',
    },
    {
      id: 'event-3',
      step: 3,
      type: 'BLOCK_SCHEDULE',
      title: 'Block 0 → SM 0',
      what: '调度器把 Block 0 分配到 SM 0。',
      why: 'Block 是调度到 SM 的基本单位，一个 Block 只在一个 SM 上运行。',
      block: 0,
      sm: 0,
    },
    {
      id: 'event-4',
      step: 4,
      type: 'WARP_SCHEDULE',
      title: 'Warp 0 开始执行',
      what: 'Block 0 内的 Warp 0（32 线程）开始执行。',
      why: 'Warp 是 SM 内真正的调度与执行单位。',
      block: 0,
      warp: 0,
      sm: 0,
    },
    {
      id: 'event-5',
      step: 5,
      type: 'MEMORY_LOAD',
      title: '取 A Tile：HBM → L2',
      what: '将 A[0,0] 从 HBM 读入 L2 Cache。',
      why: '计算前需要先把数据从显存取到更快的缓存层级。',
      block: 0,
      sm: 0,
      source: 'HBM',
      destination: 'L2',
      tensor: 'A',
      tile: { tensor: 'A', tileRow: 0, tileCol: 0, label: 'A[0,0]' },
    },
    {
      id: 'event-6',
      step: 6,
      type: 'MEMORY_MOVE',
      title: 'Load A Tile',
      what: '将 A 的当前 Tile 从 L2 Cache 搬运到 Shared Memory。',
      why: '同一 Tile 会被一个 Thread Block 内多个线程重复使用，先搬入 Shared Memory 可以减少重复访问更慢的全局内存。',
      block: 0,
      sm: 0,
      source: 'L2',
      destination: 'SHARED_MEMORY',
      tensor: 'A',
      tile: { tensor: 'A', tileRow: 0, tileCol: 0, label: 'A[0,0]' },
    },
    {
      id: 'event-7',
      step: 7,
      type: 'SYNC',
      title: '线程同步 __syncthreads()',
      what: 'Block 内所有线程等待数据搬运完成。',
      why: '必须保证 Shared Memory 数据就绪后才能开始计算。',
      block: 0,
      sm: 0,
    },
    {
      id: 'event-8',
      step: 8,
      type: 'MMA',
      title: 'Tensor Core 执行 MMA',
      what: 'Tensor Core 执行 D = A × B + C 的矩阵乘累加。',
      why: 'Tensor Core 是专为矩阵乘累加设计的硬件单元。',
      block: 0,
      warp: 0,
      sm: 0,
    },
    {
      id: 'event-9',
      step: 9,
      type: 'MEMORY_STORE',
      title: '写回 C Tile：Register → HBM',
      what: '把结果 C[0,0] 从寄存器写回 HBM。',
      why: '累加完成后一次性写回，避免中间结果反复搬运。',
      block: 0,
      sm: 0,
      source: 'REGISTER',
      destination: 'HBM',
      tensor: 'C',
      tile: { tensor: 'C', tileRow: 0, tileCol: 0, label: 'C[0,0]' },
    },
    {
      id: 'event-10',
      step: 10,
      type: 'GEMM_END',
      title: 'GEMM 完成',
      what: 'Block 0 执行完毕，C 已写入 HBM。',
      why: '示例结束。注意：这是教学仿真，不代表真实 cycle 数。',
    },
  ],
};
